### PR TITLE
[dist] 1.1.0

### PR DESCRIPTION
**Pull request by SEAPUNK**
Changelog, from what I am looking at in the commits:

* Add TaxService API support (lpinca) 
* Add UsageCharge API support (lpinca) 
* Add ability to check API call limit (SEAPUNK & lpinca)

Ref: #92

### CODE REVIEW

**Comment by SEAPUNK** [comment]
Wait, shoot. Wrong version. Let me redo that really quickly.

**Comment by lpinca** [comment]
Thanks but the release is on hold for a reason.
I've assumed that `shopify.taxService.delete()` returns an [empty object](https://github.com/microapps/Shopify-api-node/commit/8c4cef68ce9c79f6f76e59118550a125e879b6b9#diff-a26185424d7ff01fdff1cf2283e688d6R66) like all other resources.

According to the [documentation](https://help.shopify.com/api/reference/taxservice) this is not true and the full object is returned.

We tried to to test this on a PLUS shop without success as this resource is new and doesn't work yet.
We would like to have some clarity about this before releasing 1.1.0.

If you need the API call limit feature please install from GitHub

**Comment by SEAPUNK** [comment]
Alright, I'll close this PR then, since you know when this library will be ready for 1.1.0.

To be honest, I didn't expect @alexandresaiz to [tell me to create the version](https://github.com/microapps/Shopify-api-node/issues/92#issuecomment-218858292) -- I was hoping that the maintainers would do it when they feel that a new version should be released, since I'm not really in charge of these sorts of things.

**Comment by lpinca** [comment]
Yes, sorry about that.

**Comment by alexandresaiz** [comment]
Well, I felt like some teacher coming here and asigning homework. Sorry.

**Pull request closed without merging**
